fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%env(resolve:USER_ADDRESS)%'
        sender_name: '%env(resolve:SENDER_NAME)%'
    service:
        user_manager: sonata.user.orm.user_manager
    group:
        #group_class:   FOS\UserBundle\Entity\Group
        group_class: App\Entity\Group
        group_manager: sonata.user.orm.group_manager
framework:
    serializer:
        enabled: true
    templating:
        engines: ['twig']
