sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
    title: 'Main Service'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
