# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Admin\FolderAdmin:
        arguments: [~, App\Entity\Folder, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Folder }

    App\Admin\PictureAdmin:
        arguments: [~, App\Entity\Picture, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Picture }

#mydatabase:
    # supported versions: 9.6, 10, 11
    # 9.3 is also available but not maintained upstream
#    type: postgresql:11
#    disk: 1024
